version: '3.3'

services:
  # Postgres
  db:
    image: postgres
    environment:
      - POSTGRES_USER=osmanagementuser
      - POSTGRES_PASSWORD=osmanagement
      - POSTGRES_DB=managementdb

  web:
    build: .
    command: ["python manage.py runserver"]
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
